name: deploy

on:
    push:
        branches: [master]

# Needed if your org/repo defaults GITHUB_TOKEN to read-only
permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # Install pnpm (official action)
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  # If your package.json has "packageManager": "pnpm@...", you can omit this
                  version: 10
                  run_install: false

            # Set up Node and enable pnpm caching
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: pnpm
                  # lockfile is inside the subfolder
                  cache-dependency-path: markhh/pnpm-lock.yaml

            # Install deps in the subdirectory, lockfile enforced (like `npm ci`)
            - name: Install dependencies
              working-directory: markhh
              run: pnpm install --frozen-lockfile

            # Build with pnpm; keep CI=false if your build treats warnings as errors
            - name: Build
              working-directory: markhh
              run: CI=false pnpm run build

            # Deploy the prebuilt /build to gh-pages (same approach you have now)
            - name: Deploy to gh-pages
              working-directory: markhh
              run: |
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git --work-tree build add --all
                  git commit -m "Auto deployment" || echo "No changes to commit"
                  git push origin HEAD:gh-pages --force
